### ISSUE TITLE
webhooks for async job

### ISSUE THREAD

**Issue by joearkon** [pydanny/webhooks#10]
Hi,
I just found a small issue when I tried to use `async_redis.sender` function

    senderobj = Senderable(
        wrapped, dkwargs, hash_value, ATTEMPTS, *args, **kwargs
    )

    # connection = value_in("url", dkwargs, kwargs)  # url params should be set to senderobj.url
    senderobj.url = value_in("url", dkwargs, kwargs)
    connection = value_in("connection", dkwargs, kwargs)

    @job('default', connection=connection)
    def worker(senderobj):

        return senderobj.send()

    return worker(senderobj)

I think the above code might be an issue to use async sender. If I'm wrong, please correct me. Thanks.

**Comment by pydanny** [comment]
Hi @joearkon - Apologies, but I've never tried to use the Redis Sender. That portion was a work in progress. I would love to work on this project further, but without a professional project I don't have any time to put into this project. :weary:

**Comment by joearkon** [comment]
Hello @pydanny,
Yeah, I understand. It is a bit more difficult to maintain the project without real world requirements. 
Thanks for your quick reply. Recently, we are kicking off a new project and decide to use python to set up a scaffold. Also we are looking for python-driven webhooks, the functionality is something like github webhooks. 
I was inspired after reading your project. And now our team decide to combining the webhooks with a distributed queue system. Anyway, thanks for your nice project. keep walking!!!

**Comment by pydanny** [comment]
Your team is on the right path. That's what we did at Eventbrite, we built a Webhooks system using a distributed queue (Celery). This project (pydanny/webhooks) served as a testbed for ideas, most of which were discarded because they were too complex. We found that the simpler we kept things, the more understandable (normalized) the SQL backend, the easier it was to maintain and extend.

Another we did was for the user interface was to copy everything that GitHub does for webhooks, whenever possible. Since developers use your Webhooks, it is best that you go with a proven webhooks design, and we choose GitHub. It's not the same (GitHub uses fat hooks, Eventbrite uses thin hooks).

You can at least read the docs on what we did at https://www.eventbrite.com/developer/v3/reference/webhooks/

**Comment by pydanny** [comment]
Ack! https://www.eventbrite.com/developer/v3/reference/webhooks/ and the other Eventbrite docs on Webhooks are out of date. I'll let my former co-workers there know that things need to be updated.

**Comment by joearkon** [comment]
Nice, glad to hear that. Thanks buddy!!! Also I would like to check the link you provided to see if it helps.
